// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYM7AqdRaQnNUhmJDGJilSfhh1vIJMt0',
    appId: '1:553877688071:web:5bb492122f87e1be24bfa2',
    messagingSenderId: '553877688071',
    projectId: 'todo-86fcf',
    authDomain: 'todo-86fcf.firebaseapp.com',
    storageBucket: 'todo-86fcf.appspot.com',
    measurementId: 'G-YY3L265B2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDuaZE-i7h3Je56xBOhUdY36rANMPFII',
    appId: '1:553877688071:android:ac3451f88ad437b024bfa2',
    messagingSenderId: '553877688071',
    projectId: 'todo-86fcf',
    storageBucket: 'todo-86fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9v2ErwreGHCeDiM4jtLYIcu1zI5G54M',
    appId: '1:553877688071:ios:7a4499eb1a49aaeb24bfa2',
    messagingSenderId: '553877688071',
    projectId: 'todo-86fcf',
    storageBucket: 'todo-86fcf.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9v2ErwreGHCeDiM4jtLYIcu1zI5G54M',
    appId: '1:553877688071:ios:43ed1a5df381500a24bfa2',
    messagingSenderId: '553877688071',
    projectId: 'todo-86fcf',
    storageBucket: 'todo-86fcf.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
